# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  kafka:
    image: hyperledger/fabric-kafka
    restart: always
    extends:
      file: base.yaml
      service: hosts
    environment:
      - KAFKA_MESSAGE_MAX_BYTES=103809024 # 99 * 1024 * 1024 B (比 configtx.yaml 的 AbsoluteMaxBytes 要大 1M)
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024 # 99 * 1024 * 1024 B (比 configtx.yaml 的 AbsoluteMaxBytes 要大 1M)
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false # 数据一致性在区块链环境中是至关重要的,不能从in-sync 副本（ISR）集合之外选取channel leader
      - KAFKA_NUM_PARTITIONS=1 # 每个topic 1个 partitions
      - KAFKA_MIN_INSYNC_REPLICAS=2  # ISR 当同步M个副本后才可以重新可以写,至少为2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3 # 副本因子,比kafka代理节点少 ,比 KAFKA_MIN_INSYNC_REPLICAS 要大,所以至少为3,由此得到kafka的最少节点是4个,容错一个节点
    ports:
      - 9092:9092
