# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#CA1_PRIVATE_KEY

version: '2'

services:
  ca.org2.jonluo.com:
    extends:
      file:   ../base/ca-base.yaml
      service: ca
    container_name: ca.org2.jonluo.com
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca.org2.jonluo.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.jonluo.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/d21f3f4faf484d3d44f7c6f8f8ed09129a47f8b5f1a8685623d4d24f136ea7b6_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.jonluo.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/d21f3f4faf484d3d44f7c6f8f8ed09129a47f8b5f1a8685623d4d24f136ea7b6_sk
    ports:
      - 7054:7054
    volumes:
      - ../../network-config/crypto-config/peerOrganizations/org2.jonluo.com/ca/:/etc/hyperledger/fabric-ca-server-config
