# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  peer0.org1.couchdb:
    container_name: peer0.org1.couchdb
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5984:5984
    volumes:
      # 数据固化，将数据映射到本地
      - /fabricdata/peer0org1couchdb:/opt/couchdb/data

  peer0.org1.jonluo.com:
    container_name: peer0.org1.jonluo.com
    extends:
      file: ../base/peer-base.yaml
      service: peer
    environment:
      - CORE_PEER_ID=peer0.org1.jonluo.com
      - CORE_PEER_ADDRESS=peer0.org1.jonluo.com:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.jonluo.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.jonluo.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      # CouchDB
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peer0.org1.couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
      - /var/run/:/host/var/run/
      - ../../network-config/crypto-config/peerOrganizations/org1.jonluo.com/peers/peer0.org1.jonluo.com/msp:/etc/hyperledger/fabric/msp
      - ../../network-config/crypto-config/peerOrganizations/org1.jonluo.com/peers/peer0.org1.jonluo.com/tls:/etc/hyperledger/fabric/tls
      # 数据固化，将数据映射到本地
      - /fabricdata/peer0org1:/var/hyperledger/production
    depends_on:
      - peer0.org1.couchdb

